version: '3.9'

services:
    hoteldatabase:
        container_name: hoteldatabase
        image: postgres:latest
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${HOTEL_POSTGRES_USER}
            - POSTGRES_PASSWORD=${HOTEL_POSTGRES_PASSWORD}
            - POSTGRES_DB=${HOTEL_POSTGRES_DB}
            - POSTGRES_HOST=${HOTEL_POSTGRES_HOST}
            - POSTGRES_SSLMODE=${HOTEL_POSTGRES_SSLMODE}
        ports:
            - "8081:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/hotel/data/
        networks:
            new:
                aliases:
                    - database

    hoteldatabasetest:
        container_name: hoteldatabasetest
        image: postgres:latest
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${TEST_HOTEL_POSTGRES_USER}
            - POSTGRES_PASSWORD=${TEST_HOTEL_POSTGRES_PASSWORD}
            - POSTGRES_DB=${TEST_HOTEL_POSTGRES_DB}
            - POSTGRES_HOST=${TEST_HOTEL_POSTGRES_HOST}
            - POSTGRES_SSLMODE=${TEST_HOTEL_POSTGRES_SSLMODE}
        ports:
            - "3232:5432"
        restart: unless-stopped
        volumes:
            - database-test:/var/lib/test-date/hotel/data/
        networks:
            new:
                aliases:
                    - database

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        env_file:
            - .env
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        restart: unless-stopped
        volumes:
            - pgadmin:/root/.pgadmin
        networks:
            - new

    hotel_migrate:
        container_name: hotel_migrate
        image: migrate/migrate
        restart: on-failure
        networks:
            - new
        volumes:
            - ./hotel/migrations:/hotel/migrations
        command:
            [
                "-path",
                "hotel/migrations",
                "-database",
                "postgres://user:userpass@hoteldatabase:5432/hoteldb?sslmode=disable",
                "up"
            ]
        links:
            - hoteldatabase
        depends_on:
            - hoteldatabase

    test_migrate:
        container_name: test_migrate
        image: migrate/migrate
        restart: on-failure
        networks:
            - new
        volumes:
            - ./hotel/migrations:/hotel/migrations
        command:
            [
                "-path",
                "hotel/migrations",
                "-database",
                "postgres://user:userpass@hoteldatabasetest:5432/hoteldbtest?sslmode=disable",
                "up"
            ]
        links:
            - hoteldatabasetest
        depends_on:
            - hoteldatabasetest

    hotel_service:
        container_name: hotel_service
        build:
            dockerfile: dockerfile
            context: ./hotel
        ports:
            - "5555:5555"
        env_file:
            - .env
        environment:
            - SERVER_HOST=0.0.0.0
            - ENV=prod
        tty: true
        restart: on-failure
        volumes:
            - api:/hotel/
        networks:
            - new
        depends_on:
            - hoteldatabase

networks:
    new:
        driver: bridge

volumes:
    api: null
    database-data: null
    database-test: null
    pgadmin: null
